version: "3"

networks:
  shared:

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    restart: unless-stopped
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres
    env_file:
      - .env
    command: [npm, run, dev]
    # command: sleep infinity
  webserver:
    build: ./server
    volumes:
      - ./server:/app
    restart: unless-stopped
    ports:
      - 53134:53134
    command: npm start
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fred-bot
      POSTGRES_USER: fred-bot
      POSTGRES_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - shared
