name: Update Repo and Rebuild TS

# Only runs on push to master branch
on:
  push:
    branches: [master]

jobs:
  # This workflow contains a single job called "build"
  build:
    # This runs on the self-hosted Raspberry Pi 4 in Alyssa's entertainment stand
    runs-on: [self-hosted, linux, ARM]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Pull down master
      - name: Pull from origin/master
        run: git -C ~/fred-for-discord pull
      # Move to correct folder and install any new packages
      - name: Move to Fred folder
        run:  |
        cd ~/fred-for-discord
        npm install
      # Build Typescript output files
      - name: Move to Fred folder
        run: npm run build
