name: Pull repo changes and Rebuild TS

# Only runs on push to master branch
on:
  push:
    branches: [master]

jobs:
  # This workflow updates the repo by pulling down remote changes and installing npm packes, then rebuilding TS files
  build:
    name: Update repo and rebuild
    # This runs on the self-hosted Raspberry Pi 4 in Alyssa's entertainment stand
    runs-on: [self-hosted, linux, ARM]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Pull down master
      - name: Pull from origin/master
        run: git -C ~/fred-for-discord pull\
      - name: Move to Fred folder and update packages
          run: |
            cd ~/fred-for-discord
            npm install
        # Build Typescript output files
        - name: Rebuild TS Files
          run: npm run build